#!/usr/bin/env python
import redis
import json
import argparse


def get_parser():
    parser = argparse.ArgumentParser(description='dump the data to redis')
    parser.add_argument('input', type=str, help='the file generated by scraper')
    return parser


def write_to_redis(fp, redis_connector):
    for line in fp:
        obj = json.loads(line)
        key = json.dumps({
            'brand': obj['brand'],
            'model': obj['model'],
            'body_type': obj['body_type'],
            # TODO(lniu) hard code the year here.
            'year': 2012
        })
        value = json.dumps(obj['value'])
        redis_connector.hset(obj['brand'].lower(), key, value)


def command_line_runner():
    parser = get_parser()
    args = vars(parser.parse_args())

    if not args['input']:
        parser.print_help()
        return

    fp = open(args['input'], "r")
    r = redis.StrictRedis(host='localhost', port=6379, db=0)
    write_to_redis(fp, r)


if __name__ == '__main__':
    command_line_runner()
